DROP TABLE IF EXISTS bookmarks;

CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    label TEXT NOT NULL,
    content TEXT NOT NULL
);
