DROP TABLE IF EXISTS bookmarks;
DROP TABLE iF EXISTS bookmark_captures;
DROP TABLE IF EXISTS events;

CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    label TEXT NOT NULL,
    retract INTEGER NOT NULL DEFAULT 0,
    content TEXT NOT NULL
);

CREATE TABLE bookmark_captures (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bookmark_id INTEGER,
    image_path TEXT
);

CREATE TABLE events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);